# https://taskfile.dev

version: "3"

tasks:
  deps:
    status:
      - mockery
    cmds:
      - go install github.com/vektra/mockery/v2@v2.45.0
      - go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen@latest

  mocks:
    cmds:
      - mockery

  tracegen:
    cmds:
      - telemetrygen traces --otlp-insecure --otlp-endpoint localhost:44317

  build:
    cmds:
      - go build ./...

  integration:build:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o integration-test/telegraf/etc/ ./...

  integration:run:
    dir: integration-test
    cmds:
      - docker compose up -d

  integration:stop:
    dir: integration-test
    cmds:
      - docker compose down

  integration:logs:
    dir: integration-test
    cmds:
      - docker compose logs -f telegraf
