# https://taskfile.dev

version: "3"

tasks:
  deps:
    cmds:
      - go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen@latest
      - brew install goreleaser

  tracegen:
    cmds:
      - telemetrygen traces --otlp-insecure --otlp-endpoint localhost:44317

  build:
    cmds:
      - go build ./...

  integration:build:
    aliases:
      - i:build
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o integration-test/telegraf/etc/ ./...

  integration:run:
    dir: integration-test
    aliases:
      - i:run
    cmds:
      - docker compose up -d

  integration:stop:
    dir: integration-test
    aliases:
      - i:stop
    cmds:
      - docker compose down {{.CLI_ARGS}}

  integration:logs:
    dir: integration-test
    aliases:
      - i:logs
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}
