services:
  telegraf:
    image: "telegraf:1.28"
    volumes:
      - ./telegraf/etc/telegraf:/etc/telegraf:ro
      - ./telegraf/etc/telegraf-execd-otel:/etc/telegraf-execd-otel
      - ./telegraf/etc/telegraf-plugins:/etc/telegraf-plugins:ro
    ports:
      - "44317:4317"
      - "44318:4318"
      - "8125:8125/udp"

  ####
  # https://github.com/grafana/tempo/blob/496b450e4424aa7dadf9493adf3afeee8bb057ff/example/docker-compose/local/docker-compose.yaml
  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  tempo:
    image: *tempoImage
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml:ro
      - ./tempo/data:/var/tempo
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200" # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "9411:9411" # zipkin
    depends_on:
      - init

  grafana:
    image: grafana/grafana:10.4.2
    volumes:
      - ./grafana/var/lib/grafana:/var/lib/grafana
      - ./grafana/etc/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"
